from __future__ import annotations

from datetime import datetime, timezone

import pytest

from app.corpus_builder import build_corpus
from app.model.grid_search import (
    DEFER_CUTOFF_GRID,
    SCARCITY_THRESHOLD_GRID,
    WEIGHT_RATIO_GRID,
    run_grid_search,
)
from app.model.seeds import PROPOSAL_SEED


@pytest.fixture(scope="module")
def small_corpus():
    # A smaller n than the real n=1200 headline run, purely for test speed -- the
    # grid-search mechanism itself is what's under test here, not the specific
    # numbers a full-size run would produce (those are covered by the real,
    # committed backend/data/playbook_tuned_weights.json, generated by app.model.
    # grid_search.main() against the real corpus).
    return build_corpus(n=300, seed=PROPOSAL_SEED, batch_simulated_start_at=datetime(2026, 1, 1, tzinfo=timezone.utc))


@pytest.fixture(scope="module")
def result(small_corpus):
    return run_grid_search(corpus=small_corpus)


def test_grid_search_scores_every_combination(result):
    _, points = result
    expected = len(WEIGHT_RATIO_GRID) * len(SCARCITY_THRESHOLD_GRID) * len(DEFER_CUTOFF_GRID)
    assert len(points) == expected
    seen = {(p.weight_ratio, p.scarcity_threshold, p.defer_cutoff) for p in points}
    assert len(seen) == expected, "every grid point should be distinct"


def test_winner_is_a_well_formed_non_abstained_playbook(result):
    winner, _ = result
    assert winner.abstained is False
    assert winner.provider == "grid_search"
    assert winner.model_id == "deterministic"
    assert winner.synthesized_from_seed == PROPOSAL_SEED
    assert winner.weight_for("technical") == 1.0  # fixed reference weight
    assert winner.weight_for("soft") in WEIGHT_RATIO_GRID
    assert winner.scarcity_remaining_budget_threshold in SCARCITY_THRESHOLD_GRID
    assert winner.defer_priority_cutoff in DEFER_CUTOFF_GRID


def test_winner_actually_maximizes_the_objective(result):
    """Direct proof the selection logic picked the true best point, not just *a*
    point -- re-derive the max independently from the scored list and compare."""
    winner, points = result
    best_point = max(points, key=lambda p: (p.net_value_paise, p.recovery_rate))
    assert winner.weight_for("soft") == best_point.weight_ratio
    assert winner.scarcity_remaining_budget_threshold == best_point.scarcity_threshold
    assert winner.defer_priority_cutoff == best_point.defer_cutoff

    # No other scored point should beat the winner on the objective (tie allowed).
    for p in points:
        assert (p.net_value_paise, p.recovery_rate) <= (best_point.net_value_paise, best_point.recovery_rate)


def test_grid_search_is_deterministic(small_corpus):
    winner_a, points_a = run_grid_search(corpus=small_corpus)
    winner_b, points_b = run_grid_search(corpus=small_corpus)
    assert winner_a == winner_b
    assert points_a == points_b


def test_never_touches_a_held_out_seed():
    """Structural guard against leaking held-out data into the same selection process
    later evaluated against it: grid search never imports app.model.seeds.HELD_OUT_SEEDS
    (mentioning the name in a comment/docstring, as this module's own module docstring
    does to explain the design, is fine -- importing and using it would not be)."""
    import ast
    from pathlib import Path

    path = Path(__file__).resolve().parent.parent / "app" / "model" / "grid_search.py"
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    imported_names = {
        alias.asname or alias.name
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom)
        for alias in node.names
    }
    assert "HELD_OUT_SEEDS" not in imported_names
